### PR TITLE
Store DGraph data in Docker volumes, instead of leaving in container fs.

### PR DESCRIPTION
**Pull request by inickles-grapl**
### Which issue does this PR correspond to?

https://github.com/grapl-security/issue-tracker/issues/900

### What changes does this PR make to Grapl? Why?

This has Nomad use a Docker volume for storing Dgraph data, allowing it to persist across container resets, which can happen from time to time. This prevents data loss observed during local grapl development. By decoupling Dgraph storage from the execution, I no longer notice when Nomad jobs reset.

Note to reviewers: I'm looking for input on two things:
1. Is there a better way to define these volumes mounts once and refer to them in each task stanza?
2. I'm just piggy-backing off of the auto-label used by the Makefile, which should probably be given a better name (key) and the comments should be updated.

### How were these changes tested?

I tested similar changes in my `inickles/dropper` branch.

### CODE REVIEW

**Comment by wimax-grapl** [comment]
> Is there a better way to define these volumes mounts once and refer to them in each task stanza?
Unless I'm missing something big, I have yet to find a way to not repeat **_stanzas_** in HCL2. However, you could do something like the following:

```
locals {
  dgraph_volume_args = {
    target = "/dgraph"
    source = "grapl-dgraph"
    # ...
  }
}
 
...later...


        mount {
          type     = "volume"
          target   = local.dgraph_volume_args["target"]
          source   = local.dgraph_volume_args["source"]
``` 
that is to say, you can deduplicate the values of the fields, but not the `volume { }` stanza itself.

I'm not necessarily sure it's worth it, but I don't hate it.
---

> I'm just piggy-backing off of the auto-label used by the Makefile, which should probably be given a better name (key) and the comments should be updated.
yeah, i'm down with you changing that around if you'd like

**Comment by inickles-grapl** [comment]
Damn, looks like we can't have dots in some names, like for docker volume labels, per HCL 2. Unless I'm missing something, that's a little unfortunate, but something we can still work with.

**Comment by twunderlich-grapl** [comment]
@inickles-grapl ,
Regarding how to DRY this up, Max's solution of using local variables is a good one. We could also switch to using either levant or nomad-pack (in alpha/beta) in order to use go-templates with nomad files, but I was hoping to wait until nomad-pack was stable to do that. Long-term that's the right approach

**Comment by inickles-grapl** [comment]
> @inickles-grapl , Regarding how to DRY this up, Max's solution of using local variables is a good one. We could also switch to using either levant or nomad-pack (in alpha/beta) in order to use go-templates with nomad files, but I was hoping to wait until nomad-pack was stable to do that. Long-term that's the right approach

I like the idea of using something like that, but personally I think I'd prefer to have that be a different PR and keep with Max's solution for this one. How does that sound?

**Review by twunderlich-grapl — APPROVED** [review]

**Comment by inickles-grapl** [comment]
@twunderlich-grapl ty for the approval 🙏 

@wimax-grapl I'm interested in your thoughts on the third commit I added.

**Comment by wimax-grapl** [comment]
Perhaps there's something creative we can do with
https://www.pulumi.com/registry/packages/docker/api-docs/volume/

where we also set the volume as a stateful-resource-to-be-deleted. We'd have to set up that volume on every nomad-agent host, though, which gets.... complicated.... i think....?

**Comment by inickles-grapl** [comment]
> Perhaps there's something creative we can do with https://www.pulumi.com/registry/packages/docker/api-docs/volume/
> 
> where we also set the volume as a stateful-resource-to-be-deleted. We'd have to set up that volume on every nomad-agent host, though, which gets.... complicated.... i think....?

Couldn't we just use that to create/define the Docker volume before Nomad tries to use it?

**Comment by wimax-grapl** [comment]
Yes, -but- the problem is that - unlike on our machines, where the Nomad agent is the same computer as the one executing Pulumi - here, the pulumi-runner is in Buildkite and needs to inform every Nomad Agent machine to create (or destroy) that volume

**Comment by inickles-grapl** [comment]
> Yes, -but- the problem is that - unlike on our machines, where the Nomad agent is the same computer as the one executing Pulumi - here, the pulumi-runner is in Buildkite and needs to inform every Nomad Agent machine to create (or destroy) that volume

Gotcha, makes sense.

**Pull request merged**
