### PR TITLE
Fix engagement-creator zip packaging for AWS

### PR DESCRIPTION
**Pull request by inickles-grapl**
### Which issue does this PR correspond to?

Started seeing an error for engagement-creator:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'engagement-creator': No module named 'engagement-creator'
```

### What changes does this PR make to Grapl? Why?

This PR does a couple things:

1. Change the zip package layout for engagement-creator to be consistent with other packages and in a way that is expected for AWS lambda.
2. Doing a `npm i` in a fresh src/js/grapl-cdk dir resulted in the package-lock.json diff. Figured might as well include here.

### How were these changes tested?

~I tested 1. above by standard steps for build and cdk deploy. For 2. I didn't do that, I just changed the entrypoint value in the AWS Console and submitted new test data, which succeeded with an engagement created in the Grapl UI. I made sure have the value I used there match what I put in the CDK.~

Previous test was apparently on a stale build, seemingly due to not having `rm dist/` before build - https://github.com/grapl-security/grapl/issues/386. Did a rebuild after `rm -rf dist/` and deployed to AWS. Sent new test data and verified it showed up in the engagement. 👍

### CODE REVIEW

**Review by jgrillo-grapl — APPROVED** [review]
LGTM

**Review by wimax-grapl — CHANGES_REQUESTED** [review]
undo this pls :)

**Comment by inickles-grapl** [comment]
> undo this pls :)

done

**Comment by inickles-grapl** [comment]
Will update the PR description

**Pull request merged**
